### ISSUE TITLE
Support v0.7

### ISSUE THREAD

**Issue by dodikuswono** [simb/FlashSocket.IO#1]
Any plan to update support for socket v0.7 ?

**Comment by simb** [comment]
Yes, when 0.7 is released (or if I get time to look at it before) I'll update the library.

**Comment by dodikuswono** [comment]
Thanks simb.
It's 2 hours ago released. Check this: http://socket.io/announcement.html.

**Comment by simb** [comment]
Then I'll have to put that on my list of things to start on tonight :)

**Comment by dodikuswono** [comment]
Nice. If only I knew Action Script, i will help.

Happy coding and get some coffe :)

**Comment by simb** [comment]
Hi, I actually spent some time on this a couple weekends ago and got most of the functionality working. The piece that is missing is the custom namespaces. but all the messages, events and json stuff work correctly.

Is this something you would like to test? I dont have any projects going using 0.7 yet.

Check the 0.7 branch of this repo.

Thanks,
sim

**Comment by dodikuswono** [comment]
Cool stuff. I will try it. I am currently in a project that use FlashSocket.IO as client, but i focused on server-side instead.

Hope i can test it soon.

**Comment by jeton** [comment]
I'd be interesting in testing for .7. Am looking to implement it into an upcoming project.

**Comment by simb** [comment]
@jeton Great! I'll try to get the readme updated as the syntax of things has changed a little bit with the new features.

When do you think you will have time to play, and what will make it easier for you to do that?  I'll probably need to release a 0.7_alpha-1 swc.

**Comment by simb** [comment]
This now works against 0.7 and 0.8 with the code from the 0.7.x branch or the swcs located here https://github.com/simb/FlashSocket.IO/downloads

**Comment by jeton** [comment]
@simb let's have a crack at it, see how I get on. thanks
