### ISSUE TITLE
Support for multibyte encodings

### ISSUE THREAD

**Issue by AlexeyKupershtokh** [simb/FlashSocket.IO#10]
As we can see in our tests, multibyte data in Russian is not parsed by Flashsocket.io correctly. It's processed as a single byte encoding, therefore russian words sent from server as
"Ядерный перец"
accepted on the flash side as 
"Ð¯Ð´ÐµÑÐ½ÑÐ¹ Ð¿ÐµÑÐµÑ¿" (note 2 times more symbols).

In our project we've resolved this issue by using decodeURIComponent() instead of unescape() function in Flashsocket.as sources.

**Comment by simb** [comment]
Feel free to submit a pull request with your changes.  If they dont break the normal encoding I have no issue pulling in the submission.

Thanks,

Simeon Bateman

Principal Instigator
PNW Rain LLC
simeon@pnwrain.com
503-616-4405

**Comment by simb** [comment]
This should be resolved via the fix patch submitted in issue #14
