### ISSUE TITLE
I need a simple example

### ISSUE THREAD

**Issue by billidani7** [simb/FlashSocket.IO#2]
Is it possible to share with us a simple example of using this class.

Thank you

**Comment by simb** [comment]
I have a couple applications in other repositories that are using this.

A very simple one is here: https://github.com/simb/FlashSocketDemo/blob/master/src/FlashSocketDemo.mxml

This is a flex application which can either be compiled with the Flash Builder product from adobe, or using mxmlc from the open source flex sdk.

A less simple application can be found here: https://github.com/simb/JasS/tree/master/07_Socket.IO_Chat
