### ISSUE TITLE
Access of undefined  receiveEvents

### ISSUE THREAD

**Issue by billidani7** [simb/FlashSocket.IO#3]
Thank you very much for the code but I have a problem

line 88 in FlashSocket.as

the statement  var event:Object = (e.target as WebSocket).receiveEvents();  (line 88 in FlashSocket.as), says "Access of undefined  receiveEvents".

Please help

**Comment by simb** [comment]
Are you still having this issue? Can you check against the 0.7 branch since I am updating it for the new socket.io?

**Comment by simb** [comment]
I never heard back on this so I am going to assume its fixed in the new branch
