### ISSUE TITLE
cant seem to connect

### ISSUE THREAD

**Issue by ghost** [simb/FlashSocket.IO#5]
i am very eager to try out flashsocket.io. after several attempts with 0.6 and also your 0.7 swc i cant seem to connect. i also tried different server implementations with different version of socket.io 0.6 and 0.7. the closest results i got were from your 0.7 alpha swc together with socket.io 0.7.11. flash connected but ended with a "client not handshaken client should reconnect" warning. on other 0.7 tries i got away with the "unknown transport: flashsocket" warning.

any ideas what could have been missing?

regards

**Comment by simb** [comment]
Hey There,  with the new 0.7.x branch you only have to use the host and port in the connect arguments.  Please see the new example in the README here https://github.com/simb/FlashSocket.IO/blob/0.7.x/README.md

**Comment by edgarmiranda** [comment]
I'm getting the same issue with the current repo. I keep getting the following on the server... I'm using the example that is in the repo

   debug - client authorized
   info  - handshake authorized 1834555772090064836
   warn  - unknown transport: "flashsocket"

Any ideas?

**Comment by benjaminbarbe** [comment]
@edgarmiranda 

> io = io.listen(app, {transports:[**'flashsocket'**, 'websocket', 'htmlfile', 'xhr-polling', 'jsonp-polling']});

**Comment by vsaravind007** [comment]
@edgarmiranda, you're getting this error because you haven't set the transport format properly! To make it work, just add this code to your Server.js file:

io.set('transports', ['websocket', 'flashsocket', 'htmlfile', 'xhr-polling', 'jsonp-polling']);

For socket.io v0.9
