### ISSUE TITLE
I could not connect with the help of examples.

### ISSUE THREAD

**Issue by Astraport** [simb/FlashSocket.IO#7]
UPDATE. Delete old question.

With great difficulty I managed to connect only after I found the file app.js.
I also corrected some of the code the application to work.
protected function joinHandler(event:Event):void
            {
                socket.send("USERNAME:" + loginForm.username.text); 
                vs.selectedIndex = 1; //add this line
            }
And change:
socket = new FlashSocket("localhost:9202"); //instead of "ws://localhost:9202/socket.io/flashsocket"

But I still cannot connect to exchange messages between clients. Each client sends a message to the server (this is seen in the log console), but it is not sent to all participants in the chat.

How can change app.js that massage will send all cliens?

Thank you.

**Comment by edgarmiranda** [comment]
Where is the app.js file are talking about?
