### ISSUE TITLE
Cannot connect using example.  "Variable URLUtil not defined"

### ISSUE THREAD

**Issue by matt-callanan** [simb/FlashSocket.IO#8]
Need to use FlashSocket.IO without Flex.  I am trying to just the fx:Script portion of the example in the README.   This compiles fine, and connects to the server, but never handshakes.  It throws this error:  "Variable URLUtil not defined", when it tries to pull it it in the following lines from FlashSocket.as

var policyUrl:String = "xmlsocket://" + URLUtil.getServerName(wsUrl) + ":843";
return (URLUtil.getProtocol(this.callerUrl) + "://" +
URLUtil.getServerNameWithPort(this.callerUrl)).toLowerCase();

**Comment by Dasbachc** [comment]
I'm having the same issue, were you able to solve this?

**Comment by hdoshi** [comment]
I am having the same issue. Any ideas on way to solve it ?

**Comment by gauravrane** [comment]
Include the swc's from the Flash Builder 4.6.0 Flex SDK that should solve the problem. They are in the sdks>4.6.0>frameworks>libs folder under your Flash Builder folder.
