### ISSUE TITLE
feature requests: callbacks on event

### ISSUE THREAD

**Issue by matt-callanan** [simb/FlashSocket.IO#9]
Requesting callbacks on events, per our quick email exchange.

Here's how it works in node:

Client:

socket.emit('test', { an: "object", from: "the client" }, function(response) {
  //do stuff with response, which == { an: "object", from: "the server" }
});

Server:

socket.on('test', function(message, callback) {
 //do stuff with message, which == { an: "object", from: "the client" }
 callback({ an: "object", from: "the server" });
});

**Comment by simb** [comment]
this was added via bwillard in a recent addition.
